{% set name = "kiconthemes" %}
{% set version = "5.69.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kiconthemes-{{ version }}.tar.xz
  sha256: 9ce961b79f13435f3db397a52a40787d6469da4b3a21a6494c2f25f86f14e532

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kiconthemes', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - karchive
    - ki18n
    - kconfig
    - kcoreaddons
    - kconfigwidgets
    - kitemviews
    - kwidgetsaddons

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5IconThemes.so

about:
  home: https://api.kde.org/frameworks/kiconthemes/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Icon GUI utilities
  description: |
    This library contains classes to improve the handling of icons in applications
    using the KDE Frameworks.
  dev_url: https://cgit.kde.org/kiconthemes.git/tree

extra:
  recipe-maintainers:
    - scopatz
