{% set name = "kiconthemes" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kiconthemes-{{ version }}.tar.xz
  sha256: f51f0c75f50da3d119448f387c65fa69785c2c1bc82b61407bb92bf80cab31b5

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kiconthemes', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - karchive >={{ version }}
    - ki18n >={{ version }}
    - kconfig >={{ version }}
    - kcoreaddons >={{ version }}
    - kconfigwidgets >={{ version }}
    - kitemviews >={{ version }}
    - kwidgetsaddons >={{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5IconThemes.so

about:
  home: https://api.kde.org/frameworks/kiconthemes/html/index.html
  license: GPL-2.0-only AND GPL-3.0-only AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-2.1-only AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-GPL AND LicenseRef-KDE-Accepted-LGPL
  license_file:
    - LICENSES/GPL-2.0-only.txt
    - LICENSES/GPL-3.0-only.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-GPL.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: Icon GUI utilities
  description: |
    This library contains classes to improve the handling of icons in applications
    using the KDE Frameworks.
  dev_url: https://cgit.kde.org/kiconthemes.git/tree

extra:
  recipe-maintainers:
    - scopatz
