{% set name = "kiconthemes" %}
{% set version = "5.71.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kiconthemes-{{ version }}.tar.xz
  sha256: 3fa986207e9d967840bd7a3f1af1e4d0105905012a0e4cf56f7ef1b3740b3496

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kiconthemes', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - karchive >={{ version }}
    - ki18n >={{ version }}
    - kconfig >={{ version }}
    - kcoreaddons >={{ version }}
    - kconfigwidgets >={{ version }}
    - kitemviews >={{ version }}
    - kwidgetsaddons >={{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5IconThemes.so

about:
  home: https://api.kde.org/frameworks/kiconthemes/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Icon GUI utilities
  description: |
    This library contains classes to improve the handling of icons in applications
    using the KDE Frameworks.
  dev_url: https://cgit.kde.org/kiconthemes.git/tree

extra:
  recipe-maintainers:
    - scopatz
